name: 'Teams notify'
description: 'Send an Adaptive Card payload to a Teams incoming webhook'
inputs:
  webhook:
    description: 'Teams incoming webhook URL'
    required: true
  card:
    description: 'Adaptive Card JSON payload'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send Adaptive Card to Teams webhook
      shell: bash
      run: |
        set -e
        printf "%s" "${{ inputs.card }}" > /tmp/card.json
        curl -s -H 'Content-Type: application/json' -d @/tmp/card.json "${{ inputs.webhook }}" || true
