#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node ./scripts/precommit/validate-branch.js || exit 1
npx lint-staged || exit 1
node ./scripts/precommit/ensure-changeset.js || exit 1
npm run test:structure || exit 1
