#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit checks..."
# Validate branch name
node ./scripts/precommit/validate-branch.js || exit 1
# Run lint-staged
npx lint-staged || exit 1
# Ensure a changeset file is staged
node ./scripts/precommit/ensure-changeset.js || exit 1
# Enforce test structure
npm run test:structure || exit 1
