name: 'Publish agent'
description: 'Publish an npm package from a given folder to npm or an Artifactory registry'
inputs:
  folder:
    description: 'Path to package folder'
    required: true
  registry-url:
    description: 'Optional registry URL to publish to (overrides npmjs)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Publish package
      shell: bash
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |
        set -e
        cd "${{ inputs.folder }}"
        if [ -f package.json ]; then
          npm ci
          npm run build --if-present || true
          if [ -n "${{ inputs.registry-url }}" ] || [ -n "$ARTIFACTORY_URL" ]; then
            REG=${{ inputs.registry-url }}
            if [ -z "$REG" ]; then REG=$ARTIFACTORY_URL; fi
            npm config set registry "$REG"
            if [ -n "$ARTIFACTORY_PASSWORD" ]; then
              # best-effort auth; may require repo-specific config
              echo "//${REG#*://}:_authToken=$ARTIFACTORY_PASSWORD" >> ~/.npmrc || true
            fi
            npm publish || true
          else
            if [ -n "$NPM_TOKEN" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm publish --access public || true
            else
              echo "No publish token provided; skipping publish"
            fi
          fi
        else
          echo "No package.json in $PWD"
        fi
