name: 'Backend template agent'
description: 'Run backend-specific checks/tasks'
inputs:
  folder:
    description: 'Path to backend folder (defaults to template root)'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Run backend checks
      shell: bash
      run: |
        set -e
        cd "${{ inputs.folder }}"
        if [ -f package.json ]; then
          npm ci
          npm run lint --if-present || true
          npm test --if-present || true
        fi
